### ISSUE TITLE
Getting a Plaid API key

### ISSUE THREAD

**Issue by Klaudioz** [bloblems/BalanceScriptableWidget#1]
Hello, can you please describe how I can get a Plaid API Development/Production key?

I don't know which options should I select from [here](https://dashboard.plaid.com/overview):

<img width="982" alt="image" src="https://user-images.githubusercontent.com/632625/183213753-2b204689-bc60-40f3-bb1a-2c99ebdeed96.png">

Thank you.

**Comment by bloblems** [comment]
Yes of course, Once youve created an account on Plaid.com you must put in a request to be given your own personal Dev/Prod key, it usually takes 1-2 days.

Here is the differences between environments.

> SANDBOX - (FREE)  fake data that free to use to help with configuring everything.

> DEVELOPMENT - (FREE)this one can be configured to show real time data, the biggest limitation being that it does not have Oauth, which is needed for some banks such as Chase. If your bank doesnt need Oauth you can indefinitely use this. attached is a support answer I got when setting this up.
![8A4D68ED-4E04-426B-BB30-4D9F5A43054F](https://user-images.githubusercontent.com/47994202/183218225-63386642-c332-4354-95fa-15076f513016.jpeg)

> PRODUCTION - (METERED .10/call) this one lets you have full access to the complete API with Oauth configuration as well as other call capabilities. This widget uses only the Balance endpoint so no authorization passed basic setup is needed.

**Comment by Klaudioz** [comment]
So, I guess I need to request Production access.

When you see **Dev/Prod**, is really confusing. Is it Development, Production, both of them?

**Comment by bloblems** [comment]
You're right I could see how it could be confused as asking for both, I went ahead and corrected that in the Read Me.
